### ISSUE TITLE
Contract address variables should start with symbol

### ISSUE THREAD

**Issue by jrriehl** [fetchai/jenesis#131]
To improve clarity and eliminate any chance of conflict with string values, let's require that contract address variables start with the symbol `$` as in a bash script. For example:
```toml
[profile.testing.contracts.swap_contract]
...
[profile.testing.contracts.income_distributor]
...

[profile.testing.contracts.income_distributor.init]
sc_address = "$swap_contract"
```
