### ISSUE TITLE
Allow init_args to point to contract address

### ISSUE THREAD

**Issue by jrriehl** [fetchai/jenesis#98]
It's common to deploy multiple contracts in which some of these contracts are instantiated with the addresses of some of the other contracts. Provided that there are no circular dependencies, this should be possible to automate. For example, a user could input:

```toml
[profile.testing.contracts.swap_contract]
...
[profile.testing.contracts.income_distributor]
...

[profile.testing.contracts.income_distributor.init]
sc_address = contracts.swap_contract.address
```
There may need to be some punctuation around `contracts.swap_contract.address`
